name: easy_ai_reading

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./tmp:/app/tmp
      - ./static/html:/app/static/html
      - ./.env:/app/.env
    env_file:
      - .env
    restart: always
    labels:
      - "com.docker.compose.project=easy_ai_reading"
      - "com.docker.compose.service=web"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
